services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: fluxdoc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # MinIO 오브젝트 스토리지
  minio:
    image: minio/minio
    container_name: fluxdoc-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-storage:/data

  # 애플리케이션 (필요시 추가)
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql
#      - minio
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fluxdoc
#      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
#      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
#      - MINIO_ENDPOINT=http://minio:9000
#      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
#      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}

volumes:
  mysql-data:
  minio-storage:

networks:
  default:
    driver: bridge